#!/usr/bin/env zsh -i

# Auto-generated by Voodoo
# First-time script for project setup (DELETE ME AFTER RUNNING!)

DOCS_DIR=~/dev/githubdocs

print Setting up your virtualenv

rmvirtualenv alexa_leaf
if [ $? -ne 0 ]; then
    print Removing old virtualenv failed
    exit -1
fi
mkvirtualenv alexa_leaf
if [ $? -ne 0 ]; then
    print Making alexa_leaf Virtual env failed
    exit -1
fi

workon alexa_leaf
if [ $? -ne 0 ]; then
    print Could not switch to alexa_leaf
    exit -1
fi
print Working in virtualenv alexa_leaf


# Set up the pip packages
pip install pytest mock pytest-cov python-coveralls coverage sphinx tox restview
#pip install sphinx restview
echo "cd ~/dev/alexa_leaf" >> ~/dev/envs/alexa_leaf/bin/postactivate

# Start python develop
python setup.py develop

# Initialize the git repo
github_remote='git@github.com:virantha/alexa_leaf.git'
git init
git remote add origin $github_remote
git add .
git commit -am "Setting up new project alexa_leaf"

# Prompt if we want to push to remote git
read -q "REPLY?Create remote repository at $github_remote [y/N]?"
if [[  $REPLY == y ]]; then
    curl --data '{"name":"alexa_leaf", "description":""}' --user "virantha" https://api.github.com/user/repos
fi

read -q "REPLY?Push to remote repository $github_remote [y/N]?"
if [[  $REPLY == y ]]; then
    git push -u origin master
fi

print
# Create the docs repository
current_dir=`pwd`
read -q "REPLY?Create and push docs to $github_remote [y/N]?"
if [[  $REPLY == y ]]; then
    # Go to the docs build dir, and check out our repo
    cd $DOCS_DIR
    git clone https://github.com/virantha/alexa_leaf.git
    cd alexa_leaf
    git checkout --orphan gh-pages
    git rm -rf .

    cd $current_dir/docs
    pip install sphinx
    make html
    cd $DOCS_DIR
    cd alexa_leaf
    touch .nojekyll
    git add .
    git commit -m "docs"
    git push origin gh-pages

fi